name: Build & Deploy code

on: [push, pull_request]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Pulls git repo
        uses: actions/checkout@v4
      - name: Setup python3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
